"""revert chat session user_id to not null

Revision ID: 20a3ac3752f9
Revises: e28d392d5609
Create Date: 2026-02-02 22:31:51.246904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '20a3ac3752f9'
down_revision: Union[str, None] = 'e28d392d5609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_tickets')
    op.drop_table('chat_messages')
    op.drop_table('ai_knowledge_base')
    op.drop_table('chat_sessions')
    op.drop_table('ticket_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_messages',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('ticket_id', sa.CHAR(length=32), nullable=False),
    sa.Column('sender_id', sa.CHAR(length=32), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), nullable=False),
    sa.Column('attachments', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('session_metadata', sqlite.JSON(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('ai_knowledge_base',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('session_id', sa.CHAR(length=32), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=5), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('message_metadata', sqlite.JSON(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=False),
    sa.Column('category', sa.VARCHAR(length=14), nullable=False),
    sa.Column('assigned_agent_id', sa.CHAR(length=32), nullable=True),
    sa.Column('resolution', sa.TEXT(), nullable=True),
    sa.Column('ticket_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
